### ISSUE TITLE
Support deep links for various payment types

### ISSUE THREAD

**Issue by roeierez** [breez/c-breez#333]
We need to add deep link as we have in Breez wallet for lightning invoices, lnurl protocol, etc...

**Comment by erdemyerebasmaz** [comment]
> > It seems to work when the app is closed but when the app is in the background it crashes and I click a lightning link (e.g lightning://lnurl1dp68gurn8ghj7ctsdyh8g6tswp5kutndv5hhvv30d3hz7urp0yhkvv3sxucrjcfcxqckvd3svcunwer9xvurzdpnxv6xzvfevcerzdenvd3rgcm9vvenzdnzvsukgv3sxasnzvnpxsmnxcmpvser2wrxxyrtgrh2)
> 
> A bit late to figure this out but unlike Android, iOS(16.2) does not list all apps that can handle the link. It seems to select a random app that can handle the link and ignores others. Let's say app 'X' is selected, it suggests to open the link with app 'X' and only app 'X' until it is uninstalled. which kept me up all night thinking deep link wasn't working at all. I was able to reproduce your case on iOS afterwards.

Good news, the crash I encountered on iOS wasn't related to deep links. After digging the forums I ran into this information.

> In iOS 14+, debug mode Flutter apps can only be launched from Flutter tooling, IDEs with Flutter plugins or from Xcode.
> 
> Alternatively, build in profile or release modes to enable launching from the home screen.

Our app isn’t configured to run on release mode so I created a sample flutter app to test this.
This screen with the exact message showed up after I tried to launch the app after severing it's connection from XCode on debug mode. I’m not sure why our app crashes immediately instead of showing this screen.
![96749967-1908-48FA-A7D2-372DD34884DD](https://user-images.githubusercontent.com/4012752/213029108-746baeaf-1f99-444a-9527-6573eb85fd33.png)
Consecutive launchs were also successful on release mode.

I will ready our environment for building in release mode and confirm deep links work as expected when app is in closed state on iOS, or find out if a customization is needed similar to launchMode change we did on Android.

**Comment by roeierez** [comment]
What do you mean by _ready our environment to build in release mode_?
Currently I am using release mode to sign manually from the CI. Although I finally managed to make it work the testflight builds show white screen and I need to figure why, not sure it is related.

**Comment by erdemyerebasmaz** [comment]
> What do you mean by _ready our environment to build in release mode_?
> Currently I am using release mode to sign manually from the CI. Although I finally managed to make it work the testflight builds show white screen and I need to figure why, not sure it is related.

Yes, it's related, I'm having the exact issue. I assume there's a Firebase or stale-ios-build cache issue according to my research. I recreated ios folder from scratch etc. but nothing has worked so far.

**Comment by erdemyerebasmaz** [comment]
@ubbabeck  could use your help with testing deep links on iOS @roeierez Could you update TestFlight app?


You need to test with the TestFlight version because otherwise app will crash for deep links when app is closed. More details [here](https://github.com/breez/c-breez/issues/333#issuecomment-1386218521).

Other known issues on iOS is, the app only suggests the first installed app* that is associated with the deep link.
Let's say 'A Wallet' supports `lightning:` scheme and is installed before 'Breez Cloud', iOS will only suggest 'A Wallet' until it's uninstalled.

*: _They say the behavior is undefined but it was following installation date from what I can tell on my tests._

### These are the test cases:

- [ ] Click a deep link when app is closed,
- [ ] Click a deep link when app is in background,
- [ ] Click a deep link through ChromeSafariBrowser([flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview)) from app.

Report any deep links that fail to launch/open the app and the deep link isn't parsed correctly.

#### Resources that can help with test:
 - Open https://lightsats.com/signin through a browser and click the generated QR code,
 - Scan the following QR code through app and click the generated QR code from the in-app browser(ChromeSafariBrowser)
 ![frame](https://user-images.githubusercontent.com/4012752/215105046-ec007267-e891-43b6-9b78-dfe07342f015.png)

**Comment by roeierez** [comment]
> @roeierez Could you update TestFlight app?

You can start the CI of iod-build and it will be uploaded automaticaly

**Comment by ubbabeck** [comment]
# Test deep links iOS
Tests were done with https://lightning.gifts/ and https://lightsats.com/signin
### when app is closed
- Open deep link 
- Open deep link and parse 
### when app is in background
- Open deep link 
- Open deep link and parse
## Results 
### Pass:

- [ ] Open deep link when app is closed
- [ ] Open deep link when app is in background 
- [ ] Open deep link and parse when in background

### Fail:
Opening a deep link with parsing does not load properly when app is closed.
-[] Open deep link and parse when closed

**Comment by erdemyerebasmaz** [comment]
Thanks for your findings @ubbabeck👏
