### ISSUE TITLE
Full wallet test

### ISSUE THREAD

**Issue by roeierez** [breez/c-breez#353]
https://docs.google.com/document/d/1ZjYuuk-G9doY2HmPdlgXheTLMjmMAskKDV-NxBXW1KU/edit

**Comment by ubbabeck** [comment]
# Full wallet test
This is a wip 
All test have not been completed yet. 
I will link PR's or issues where needed.

### Repo state

- State of main c-Breez when test where done 5e392bb63b8f0c2ee73932fb368cbda03e436e7d
- State of main breez-sdk when test where done [be7953a64785a1704864fe1fafaabcdadf67ae1c](https://github.com/breez/breez-sdk/tree/be7953a64785a1704864fe1fafaabcdadf67ae1c)

## Test conducted on device 

- [ ] iOS
- [ ] Android

## Simulator 

- [ ] iOS
- [ ] Android

## Node
### Registrer node

- Uninstall existing installations if any, install and start the application  ✅ 
- Click Let’s Breez to create a node from scratch ✅ 
- Click Let’s Breez to create a node from scratch ❌  [Screen turns black when verifying Mnemonics](https://github.com/breez/c-breez/issues/479)

### Recover Node

- Uninstall existing installations if any, install and start the application ✅ 
- Click Restore from backup to recover an existing node  ✅ 
- Recover using credentials ✅ 
- We are being prompted with verify backup after recovery. is this necessary #475 should fix this
- Wait for the node to sync

### Start Existing Node

- After successfully registering or recovering a node, restart the application ✅ 

## Payments

### Receive with open channel
#### Precondition: New Wallet
- Create invoice for 3000 sats ✅ 
- Pay with another wallet ✅ 

### Receive with existing unconfirmed channel
- Right after  the channel opens ❌ channel seems to close
- Create invoice for 10 sats ❌
- Pay with another wallet

### Receive on-chain 

- Use Receive>Receive via BTC Address to generate address
- Send 10k sats to that address with another wallet
- Wait for the TX to get confirmed
- You can use blockchain explorers such as https://blockstream.info/
- Once confirmed, open the wallet and wait for a successful swap

### Refund
- Use Receive>Receive via BTC Address to generate address
- Send a small amount below threshold to that address with another wallet
- Refund after timeout(Refund isn’t implemented yet)
### Close channel & Withdraw (Unexpected Funds)
- Use developers screen to close all channels by choosing: closeAllChannels
- Go to the payments list and make sure you see the closed channel (pending) at the top of the list
- Wait for 6 confirmations (maybe more depends on greenlight) to see that the closed channel is no longer pending in the list.
- Upon confirmation you should see a warning icon on the top right corner (unexpected funds). Clicking on it will show a page where you can send the closed channel funds on-chain. Send it to another address and make sure the fees you chose were used.
### Pay a bolt 11 Invoice
- Create an invoice using another wallet or service,
- Copy the link to clipboard and open c-Breez,
- Pay the invoice
  - The payment dialog should appear automatically when an invoice was detected in the clipboard, if it didn’t appear then it is a bug.
  - If the payment dialog does not show up or closed by accident, use Send>Paste Invoice or ID 
  - Pay the invoice
### Pay directly to a node id
- Copy a node id to clipboard and open c-Breez,
- Pay any amount
  - If the payment dialog does not show up or closed by accident, use Send>Paste Invoice or ID
### Pay LNURL
- Create a LNURL invoice
  - lightning.gifts, ln.cash,
- Pay the invoice
  - If the payment dialog does not show up or closed by accident, use Send>Paste Invoice or ID 
## Fiat (Fiat Currencies Screen)
### Select preferred fiat currencies
- Change Preferred currencies and order by d&d ✅ 
- Create invoice and use fiat currency instead of sats. ✅ 
## Security (Security Screen)
### Create PIN
- Create PIN, use different “Lock times” and test by going to background and restart ✅ 
### Enable Biometric 
- Does not work on iOS ❌
Network (Network Screen)
### Set up a custom mempool API URL
- works with local http ✅ 
- works with local https ❌
- reset does not work before after restart #issue

## CLI (Developers Screen)
### Test available commands
