### ISSUE TITLE
Wrong error message when fail to withdraw with lnurl

### ISSUE THREAD

**Issue by roeierez** [breez/c-breez#374]
I tested negative flow and tried to withdraw from tippin (https://tippin.me) and it failed (as it should because there wasn't route).
I got the following error message (see screenshot). It seems that we require the field reason but I am not sure it should be required.

![fail-withdraw](https://user-images.githubusercontent.com/5394889/213376366-1ae22da4-c183-400e-b61a-0960fab1e73c.jpg)

**Comment by ok300** [comment]
The LNURL-withdraw spec[^1] says that, when the endpoint returns an error, it should always contain a `reason`.

We could "beautify" the UI and show a generic message when the reason is not there.

This is how Wallet of Satoshi handles "invalid responses" from the LNURL endpoint:

![image0](https://user-images.githubusercontent.com/106775972/208099442-2342196e-80dc-48a1-a6f1-2894b3213446.jpeg)

Something similar could be shown every time we receive a non-compliant mis-formatted LNURL response, to be more user-friendly.

Would that be a good option?

[^1]: See step 6 in [LUD-03](https://github.com/lnurl/luds/blob/luds/03.md)

**Comment by roeierez** [comment]
Yes. 
Let's validate it and use some more friendly messages as you suggested.
