### ISSUE TITLE
Wrong fee warning message 

### ISSUE THREAD

**Issue by kingonly** [breez/c-breez#399]
Please compare this warning to Breez Mobile. I believe we have different message for an empty wallet.
![Screenshot_2023-01-21-14-11-19-50_9a3a9060ca72a38f8a1fec1d0c1a640e](https://user-images.githubusercontent.com/31890660/213866310-467f05c7-7e2b-420d-a87f-d78a2ad4a5ea.jpg)

**Comment by kingonly** [comment]
Same for Receive via BTC Address. Receive more than 0 sats has no meaning.
![Screenshot_2023-01-21-16-34-30-81_9a3a9060ca72a38f8a1fec1d0c1a640e](https://user-images.githubusercontent.com/31890660/213871661-5623f260-4abd-401b-8deb-8eaf0b18cf89.jpg)

**Comment by ok300** [comment]
I see two ways this issue could be interpreted:

A. It should be 100% identical to the Breez Mobile message, even if this means it will lose extra granularity
* Breez Mobile:
  * _A setup fee of 0.4% will be applied on the received amount._
* c-breez:
  * _A setup fee of 0.4% with a minimum of 2000 sats will be applied for receiving more than 0 sats._
  * 
B. It is fine the way it is, but the issue is fixing the zero amount in empty wallets:
* _... will be applied for receiving more than 0 sats._

@kingonly @roeierez could you please say which one is the one you mean? Thanks.

---

Background info:

In breez-mobile, the template is

> A setup fee of ${lsp.channelFeePermyriad / 100}% will be applied on the received amount.
>
> https://github.com/breez/breezmobile-features/blob/7f16ac1f278fa2f327bd67f9722e9839b6c73097/lib/widgets/lsp_fee.dart#L34

resulting in a message like

> A setup fee of 0.4% will be applied on the received amount.

In c-breez, the template is

> A setup fee of {setUpFee}% with a minimum of {minFee} will be applied for receiving more than {liquidity}.
>
> https://github.com/breez/Breez-Translations/blob/378f1e95d40fb411eca99fd669c9fb1627304bab/lib/app_en.arb#L162

with a resulting message like:

> A setup fee of 0.4% with a minimum of 2000 sats will be applied for receiving more than 0 sats.

**Comment by kingonly** [comment]
There are two templates in Breez Mobile. We also use c-breez one but only when there are existing channels.

This is from Breez Mobile:
![Screenshot_2023-01-23-21-46-54-75_73a31df444cba46df764485ac1a8c3ef](https://user-images.githubusercontent.com/31890660/214135138-d4f6e3c7-b93c-484d-9399-d79616c3dc4c.jpg)

**Comment by erdemyerebasmaz** [comment]
@ok300 Could you go over _sendMessage function of DepositWidget see if the changes you've applied in #441 apply there as well?

**Comment by ok300** [comment]
Good point @erdemyerebasmaz , I addressed it in #453
