### ISSUE TITLE
Bad 0-amount invoice UI

### ISSUE THREAD

**Issue by kingonly** [breez/c-breez#547]
Top label needs more top and bottom padding 

![Screenshot_2023-04-17-12-06-30-61_9a3a9060ca72a38f8a1fec1d0c1a640e](https://user-images.githubusercontent.com/31890660/232439193-b0cbae98-9103-40ab-9a7b-5cd331631ff8.jpg)

**Comment by erdemyerebasmaz** [comment]
The UI's code is practically the same between cBreez & Breezmobile, couldn't find the root cause but noticed `Column` alignments were behaving differently. We have a lot of `_addIfNotNull` logic, perhaps this difference is due to null safety. Will get back to investigating this at a later now. 

For now, I've applied a fix to programmatically allocate the free space around equally around dialog content.
There's still a slight difference 🤏 Here's the comparison between cBreez(Dark theme) and Breezmobile with this fix:

https://github.com/breez/c-breez/assets/4012752/49c78167-b1f9-4245-ae7c-71bf4cdb2627
