### ISSUE TITLE
Changes to list_payments interface

### ISSUE THREAD

**Issue by dangeross** [breez/c-breez#629]
PR breez/breez-sdk#463 has introduced a changes to the list_payments interface. The function now accepts a single ListPaymentsRequest argument:

```
dictionary ListPaymentsRequest {
    PaymentTypeFilter filter;
    i64? from_timestamp = null;
    i64? to_timestamp = null;
    boolean? include_failures = null;
};

[Throws=SdkError]
sequence<Payment> list_payments(ListPaymentsRequest request);
```

**Comment by erdemyerebasmaz** [comment]
I believe this is one of those cases where it's better to keep the listPayments being exposed by flutter package as it is, as seen on [sdk-flutter](https://github.com/breez/breez-sdk/blob/d90c6b7062749b59fc534778b0426e1ebc790552/libs/sdk-flutter/lib/breez_bridge.dart#L194) with it's individual params, instead of passing `ListPaymentsRequest` on each request.

`listPayments(req: ListPaymentsRequest(from_timeStamp: ****, include_failures: true));` 
this can be written as:
```
final req =  ListPaymentsRequest(from_timeStamp: ****, include_failures: true));
listPayments(req: req)...
```
but it all seems counter-intuitive compared to:
`listPayments(from_timeStamp: ****, include_failures: true);`

@dangeross @roeierez what do you think?

**Comment by dangeross** [comment]
I think we are slowly trying to unify the SDK into a request/response object interface and functions with lots of params can start to look cluttered. There is also an open PR to introduce `limit` and `offset` params, so `listPayments` will have especially lots of parameters.

How is it handled elsewhere in the flutter package with request objects (like `receiveOnchain` and `receivePayment`)?

**Comment by erdemyerebasmaz** [comment]
> I think we are slowly trying to unify the SDK into a request/response object interface and functions with lots of params can start to look cluttered. There is also an open PR to introduce `limit` and `offset` params, so `listPayments` will have especially lots of parameters.
> 
> How is it handled elsewhere in the flutter package with request objects (like `receiveOnchain` and `receivePayment`)?

Flutter people love params, the more the merrier! 😅

<img width="837" alt="Screenshot 2023-09-26 at 17 21 25" src="https://github.com/breez/c-breez/assets/4012752/5febf75d-75ac-4bb8-80f1-dadc204e5397">

The norm in Flutter is to pass multiple parameters instead of a single object that contains those parameters, as it requires less typing and removes the need to instantiate a request object.
  
  
There's usually a wrapping function that takes multiple params that are used to create a request object and then the SDK function is called with that request object.***

SDK implementations of the requests you mentioned use parameters of that request object(opening_fee_params) in multiple methods afaik, this is not the case for `list_payments`.

***: My preference as a Flutter developer is this option but it's currently not consistent across the methods in BreezSDK of sdk-flutter.

@breez/breez-developers It may be a bit outdated but some traction on https://github.com/breez/breez-sdk/pull/333 would be appreciated.

**Comment by roeierez** [comment]
The flutter interface should be the same as the udl file. We are aiming to use uniffi with flutter in the future rather than maintain the flutter-rust-bridge
