### ISSUE TITLE
Difference in the fee for opening a channel

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#643]
Reproduce: 
 - Create an invoice that requires a new channel opening
 -  Pay with another device/wallet

Result: The amount should be 2500sats and it is 2501sats. The difference is insignificant but I am not sure if there is another issue behind it.
![image](https://github.com/breez/c-breez/assets/127208515/73443436-404d-40de-b57e-f525d3764d56)

**Comment by ubbabeck** [comment]
Could it be that the +1 sat is the routing fee?

**Comment by roeierez** [comment]
No, the LSP returns two fee params options:
1: base fee 2500000 msat valid for 1 hour.
2: base fee 2500001 msat valid for 2 days.

In the default case we should create an invoice valid for an hour with the first option as fees. I think the issue is that we select the second option.
Maybe we pass explicitly that option to the sdk?

**Comment by ok300** [comment]
I tested on the SDK and the fee params when receiving with no existing channels is 2500000 msat.

However in that call we do a few things:
- fetch the LSP infos to see available fee params at this moment
- create the invoice with exactly 1 hour expiry
- look through the fee params to find the cheapest that matches 1h expiry (by comparing `now + expiry` vs `fee_params.valid_until`)

If the last check doesn't fit to the second, we will go to the next cheapest fee rate, which is for 2 days.

My theory is that, if there is some network latency so one of the calls takes a bit longer to complete, we may filter out the 1h fee rate from the LSP because its `valid_until` was maybe 1-2s in the past.

This can also happen IMO when the local time of the device is a few seconds ahead of the LSP time.

A few solutions come to mind:
- `receive_payment` could create the invoice with a default of 30 or 45 min expiry, to definitely fit within the 1h from the LSP fee params
- The LSP fee params could add a buffer of a few minutes to mitigate this. So instead of 1h and 2d, the feerate timeframes can be 1h 5m and 2d 15m.
- We could extend the API to retrieve the local time on the LSP, and base all feerate calculations on that (e.g. check `current_lsp_time + expiry <= feerate.valid_until`)

**Comment by roeierez** [comment]
@ok300 I think the solution is to pass the displayed `OpenFeeParams` that the user see to the receive_payment
